name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:

    - name: Build
      run: |
        apt-get install docker -y
        systemctl enable docker && systemctl start docker
        apt-get install -y rsync
        apt-get install -y git
