name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
        
        
        
        
