name: Go

on:
  push:
    branches: [ release-0.36 ]
  pull_request:
    branches: [ release-0.36 ]
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: release-0.36
    - name: make builder
      run: |
        make builder-build
        make clean
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
        
        
        
        
